spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://122.51.195.68:3306/blog?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 20
      initial-size: 10
      max-wait: 60000
  servlet:
    multipart:
      max-file-size: 120MB
      max-request-size: 120MB

  thymeleaf:
    cache: false
  # spring1.4.2
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.study.pagehelper.bean
  configuration:
    use-actual-param-name: true
    map-underscore-to-camel-case: true
    use-generated-keys: true


#pagehelper\u914D\u7F6E
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql